namespace Ez.Handball.Domain;

public sealed record PlayerStat(
    string PlayerId,
    string MatchId,
    string TournamentId,
    string? TournamentName,
    string Season,
    string TeamId,
    string? ClubName,
    int Goals,
    int YellowCards,
    int TwoMinuteSuspensions,
    int RedCards,
    int? HbStatzAssists = null,
    int? HbStatzSteals = null,
    int? HbStatzBlocks = null,
    int? HbStatzSaves = null,
    int? HbStatzTurnovers = null,
    int? HbStatzLegalStops = null,
    int? HbStatzShots = null,
    double? HbStatzExpectedGoals = null,
    int? HbStatzShotsFaced = null,
    double? HbStatzSavePct = null,
    double? HbStatzExpectedSaves = null,
    double? HbStatzGradeTotal = null,
    double? HbStatzGradeOffense = null,
    double? HbStatzGradeDefense = null,
    double? HbStatzGradeGoalkeeping = null);
